version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks: 
     - crm

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    links:
      - postgres
    restart: unless-stopped
    networks: 
      - crm


  spring-boot-crm-backend:
    build: ./spring-boot-crm-backend
    container_name: spring-boot-crm-backend

    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - postgres
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - crm

  angular-crm-frontend:
    build: ./angular-crm-frontend
    container_name: angular-crm-frontend
    ports:
      - 80:80
    links:
      - spring-boot-crm-backend
    networks: 
      - crm

networks:
  crm:
    driver: bridge

volumes:
  postgres:
  pgadmin: