apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-postgresql
  template:
    metadata:
      labels:
        app: springboot-k8s-postgresql
    spec:
      containers:
      - name: springboot-crud-k8s
        image: johannessiedersberger/springboot-crud-k8s:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
          - name: DB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: db-config
                key: host
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: db-config
                key: dbName
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: postgresql-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgresql-secrets
                key: password
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-postgresql
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort  
