apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels: 
    app: postgresql
    tier: database
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels: 
    app: postgresql
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql
      tier: database
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
      - name: postgresql
        image: postgres
        env: 
          - name: POSTGRESQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                  name: postgresql-secrets
                  key: password
          - name: POSTGRESQL_DATABASE
            valueFrom: 
              secretKeyRef:
                  name: db-config
                  key: dbName
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts: 
          - name: postgresql-persistent-storage
            mountPath: /var/lib/postgresql
      volumes: 
        - name: postgresql-persistent-storage
          persistentVolumeClaim: 
            claimName: postgresql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels: 
    app: postgresql
    tier: database
spec:
  selector:
    app: postgresql
    tier: database
  ports:
  - port: 3306
    targetPort: 3306

