# Use the official OpenJDK 17 base image
FROM openjdk:17-jdk-slim

COPY build/libs/spring-boot-crm-backend-0.0.1-SNAPSHOT.jar spring-boot-crm-backend-0.0.1-SNAPSHOT.jar

EXPOSE 8080

# Set the entry point to run the application
ENTRYPOINT ["java", "-jar", "spring-boot-crm-backend-0.0.1-SNAPSHOT.jar"]

